### PR TITLE
Added site playoff bracket

### PR DESCRIPTION
**Pull request by tristan-gill**
Added a new table: `playoff_series`
This table is similar to the `series` table.

Added a bunch of stuff to create, view, edit, list these new `playoff_series`. These are all very similar to their respective `series`.

Added a new page called bracket. This displays all of the `playoff_series` that exist for a defined season. It uses round and match_number to determine how to place the matches/series in the bracket. 
 - Round determines which column the match goes into
 - Match number determines which slot the match goes into within that column. 
Using incorrect numbers will horribly disfigure the layout of the bracket, but if done correctly it should look something like this.

In order for the bracket to resemble the challonge bracket someone has to make all the series. All admins have the ability to do so. Admins also see an edit tag on the bracket.

image

### CODE REVIEW

**Comment by dambrisco** [comment]
I'm not a big fan of having a new series table. It would probably make more sense to have seasons have a specified number of rounds, after which everything is assumed to be post-season games.

I'll take a closer look at the PR tomorrow to see if there's anything that would conflict with what I've suggested.

**Comment by tristan-gill** [comment]
the biggest difference between the `playoff_series` table that I added and the existing `series` table is that `playoff_series` have a `home_division_id` and an `away_division_id` since teams can be playing eachother from different divisions. 
The main reason I thought that a separate table was best was because adding a home and away division to the existing `series` table would invalidate all the existing records and we would need to make a migration task to populate the new columns. 
You guys know the code and processes better than I do so if you think modifying the `series` table to handle playoff games then it can be done moderately easily

**Comment by dambrisco** [comment]
You can derive the `division_id` for each team by joining the `team` table, so I don't believe it would be necessary to create any new columns, actually. Should *largely* eliminate the benefit of a separate table.

However, I don't have any suggestions for deriving `match_number` yet, but I suspect it might be possible to do something using SoS. Need to look a bit more at the `bracket` function.

**Comment by kabobrocks** [comment]
@tristan-gill another thing you can do is just add a t/f flag on series if it is playoffs or not

**Comment by tristan-gill** [comment]
yea ill probably get around to redoing this pr later in the week

**Pull request closed without merging**
